name: dotnet-project
on:
  push:
    branches:
      - develop
jobs:
  dotnet_project_job:
    # runs-on: 'self-hosted'
    runs-on: 'ubuntu-latest'
    steps:
      - name: git checkout to the code
        uses: actions/checkout@v5
      - name: sonarcode scan
        uses: SonarSource/sonarqube-scan-action@v3
        env:
            SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
           args: >
             -Dsonar.organization:srinuparella
             -Dsonar.projectKey:srinuparella_nopCommerce
            
      # - name: dotnet install
      #   uses: actions/checkout@v5
      #   with:
      #     dotnet-version: '9.0.100'
      # - name: dotnet publish dll
      #   run: dotnet publish -c Release  src/Presentation/Nop.Web -o dll_dir
      # - name: dotnet application run
      #   run: cd /home/ubuntu/actions-runner/_work/nopCommerce/nopCommerce/dll_dir && \
      #        dotnet Nop.web.dll
      - name: aws login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # env:
        #   AWS_REGION: ${{ env.AWS_REGION }}
          aws-region: us-east-1
      - name: Login Ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Login Docker 
        uses: docker/build-push-action@v6
      - name: build and push image
        env:
          ECR_REGISTRY: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 934545598565.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: actions
          IMAGE_TAG: latest
        run: |
          docker image build -t actions:latest . 
          docker tag actions:latest 934545598565.dkr.ecr.us-east-1.amazonaws.com/actions:latest
          docker push 934545598565.dkr.ecr.us-east-1.amazonaws.com/actions:latest
      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@0.28.0
      #   run: |
      #      trivy image 934545598565.dkr.ecr.us-east-1.amazonaws.com/actions:latest  
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 934545598565.dkr.ecr.us-east-1.amazonaws.com/actions:latest
          format: table
          ignore-unfixed: true
          vuln-type: 'os,library'
   
      # - name: Login K8s
      #   uses: actions-hub/kubectl@master
      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name richard
          kubectl get nodes
      - name: Run Pods
        run: |
          kubectl apply -f /manifestfiles/*
          kubectl get all